name: graphbind
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5
  - torchvision
  - torchaudio
  - numpy<2
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - networkx
  - biopython
  - dssp
  - pymol-open-source
  - pip
  - pip:
    - py3Dmol
    - wandb
    - python-dotenv
    - huggingface_hub
    - torch_geometric
    

